import { Request } from 'express';

// ─── Auth Types ────────────────────────────────────────
export interface JwtPayload {
    userId: string;
    email: string;
    isSuperAdmin: boolean;
    jti?: string;
}

export interface AuthenticatedRequest extends Request {
    user: JwtPayload;
    cashbookRole?: CashbookRole;
    workspaceRole?: WorkspaceRole;
}

// ─── Pagination ────────────────────────────────────────
export interface PaginationParams {
    page: number;
    limit: number;
    sortBy?: string;
    sortOrder?: 'asc' | 'desc';
}

export interface PaginatedResponse<T> {
    data: T[];
    pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
        hasNext: boolean;
        hasPrevious: boolean;
    };
}

// ─── API Response ──────────────────────────────────────
export interface ApiResponse<T = any> {
    success: boolean;
    message: string;
    data?: T;
    errors?: Record<string, string[]>;
}

// ─── Workspace Types ───────────────────────────────────
export enum WorkspaceType {
    PERSONAL = 'PERSONAL',
    BUSINESS = 'BUSINESS',
}

export enum WorkspaceRole {
    OWNER = 'OWNER',
    ADMIN = 'ADMIN',
    /**
     * Runs the operation day to day: staff, delivery, people ops and the whole
     * ticketing surface, reaching the books as far as an admin does.
     *
     * Cannot rename or delete the workspace, edit the chart of accounts, close a
     * period, post a manual journal, bulk-import members, or appoint
     * accountants — see the matrix docstring for why each is withheld.
     */
    GENERAL_MANAGER = 'GENERAL_MANAGER',
    /** Full accounting access across every book; may add sub-accountants only. */
    ACCOUNTANT = 'ACCOUNTANT',
    /** Org-level accounting access; book data limited to explicit grants. */
    SUB_ACCOUNTANT = 'SUB_ACCOUNTANT',
    /**
     * Runs projects and tasks org-wide. No financial access; books only via an
     * explicit CashbookMember row.
     *
     * Not to be confused with ProjectRole.PROJECT_MANAGER, which delegates a
     * single project. Same name, different scope.
     */
    PROJECT_MANAGER = 'PROJECT_MANAGER',
    /** People operations: attendance, leave, overtime, work reports. */
    HR = 'HR',
    /** No org-financial access. Assigned books, projects, tasks, time tracking. */
    MEMBER = 'MEMBER',
    /**
     * Developer / integration role.
     * Can create, list, and revoke API keys; view book IDs for assigned books;
     * access integration docs. No financial write access.
     */
    DEVELOPER = 'DEVELOPER',
}

/**
 * What job somebody does, as distinct from what they may do.
 *
 * Roles carry authority; tags carry assignment. A bar attendant, a maintenance
 * hand and a social media manager all hold exactly MEMBER's permissions, so
 * they are tags rather than five near-identical rows in the permission matrix.
 *
 * TICKETING is the sole exception and the sole tag that grants anything — see
 * src/core/authz/ticketing-access.ts.
 */
export enum StaffTag {
    BAR = 'BAR',
    RESTAURANT = 'RESTAURANT',
    KITCHEN = 'KITCHEN',
    TICKETING = 'TICKETING',
    MAINTENANCE = 'MAINTENANCE',
    SOCIAL_MEDIA = 'SOCIAL_MEDIA',
    SUPERVISOR = 'SUPERVISOR',
    SECURITY = 'SECURITY',
    OTHER = 'OTHER',
}

/** Modules a superadmin unlocks per organisation. */
export enum FeatureKey {
    TICKETING = 'TICKETING',
}

// ─── Cashbook Types ────────────────────────────────────
export enum CashbookRole {
    PRIMARY_ADMIN = 'PRIMARY_ADMIN',
    ADMIN = 'ADMIN',
    BOOK_ADMIN = 'BOOK_ADMIN',
    DATA_OPERATOR = 'DATA_OPERATOR',
    VIEWER = 'VIEWER',
}

export enum EntryType {
    INCOME = 'INCOME',
    EXPENSE = 'EXPENSE',
}

export enum DeleteRequestStatus {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
}

// ─── Audit Types ───────────────────────────────────────
export enum AuditAction {
    // Auth
    USER_REGISTERED = 'USER_REGISTERED',
    USER_LOGGED_IN = 'USER_LOGGED_IN',
    USER_LOGGED_OUT = 'USER_LOGGED_OUT',
    TOKEN_REFRESHED = 'TOKEN_REFRESHED',
    ALL_SESSIONS_REVOKED = 'ALL_SESSIONS_REVOKED',
    SUSPICIOUS_LOGIN = 'SUSPICIOUS_LOGIN',
    EMAIL_VERIFIED = 'EMAIL_VERIFIED',
    PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
    PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
    PASSWORD_SETUP_COMPLETED = 'PASSWORD_SETUP_COMPLETED',

    // Google OAuth
    GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS',
    GOOGLE_LOGIN_FAILED = 'GOOGLE_LOGIN_FAILED',
    GOOGLE_ACCOUNT_LINKED = 'GOOGLE_ACCOUNT_LINKED',
    GOOGLE_ACCOUNT_CREATED = 'GOOGLE_ACCOUNT_CREATED',

    // OC OAuth
    OC_LOGIN_SUCCESS = 'OC_LOGIN_SUCCESS',
    OC_LOGIN_FAILED = 'OC_LOGIN_FAILED',
    OC_ACCOUNT_LINKED = 'OC_ACCOUNT_LINKED',
    OC_ACCOUNT_CREATED = 'OC_ACCOUNT_CREATED',

    // Workspace
    WORKSPACE_CREATED = 'WORKSPACE_CREATED',
    WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
    WORKSPACE_DELETED = 'WORKSPACE_DELETED',
    MEMBER_INVITED = 'MEMBER_INVITED',
    MEMBER_IMPORTED = 'MEMBER_IMPORTED',
    MEMBER_REMOVED = 'MEMBER_REMOVED',
    MEMBER_ROLE_CHANGED = 'MEMBER_ROLE_CHANGED',

    // Cashbook
    CASHBOOK_CREATED = 'CASHBOOK_CREATED',
    CASHBOOK_UPDATED = 'CASHBOOK_UPDATED',
    CASHBOOK_DELETED = 'CASHBOOK_DELETED',
    CASHBOOK_MEMBER_ADDED = 'CASHBOOK_MEMBER_ADDED',
    CASHBOOK_MEMBER_REMOVED = 'CASHBOOK_MEMBER_REMOVED',
    CASHBOOK_MEMBER_ROLE_CHANGED = 'CASHBOOK_MEMBER_ROLE_CHANGED',
    CASHBOOK_INTEGRATION_ACTIVATED = 'CASHBOOK_INTEGRATION_ACTIVATED',

    // Entry
    ENTRY_CREATED = 'ENTRY_CREATED',
    ENTRY_UPDATED = 'ENTRY_UPDATED',
    ENTRY_DELETED = 'ENTRY_DELETED',
    ENTRY_DELETE_REQUESTED = 'ENTRY_DELETE_REQUESTED',
    ENTRY_DELETE_APPROVED = 'ENTRY_DELETE_APPROVED',
    ENTRY_DELETE_REJECTED = 'ENTRY_DELETE_REJECTED',

    // Category
    CATEGORY_CREATED = 'CATEGORY_CREATED',
    CATEGORY_UPDATED = 'CATEGORY_UPDATED',
    CATEGORY_DELETED = 'CATEGORY_DELETED',

    // Contact
    CONTACT_CREATED = 'CONTACT_CREATED',
    CONTACT_UPDATED = 'CONTACT_UPDATED',
    CONTACT_DELETED = 'CONTACT_DELETED',

    // Payment Mode
    PAYMENT_MODE_CREATED = 'PAYMENT_MODE_CREATED',
    PAYMENT_MODE_UPDATED = 'PAYMENT_MODE_UPDATED',
    PAYMENT_MODE_DELETED = 'PAYMENT_MODE_DELETED',

    // Attachment
    ATTACHMENT_UPLOADED = 'ATTACHMENT_UPLOADED',
    ATTACHMENT_DELETED = 'ATTACHMENT_DELETED',

    // Report
    REPORT_REQUESTED = 'REPORT_REQUESTED',
    REPORT_GENERATED = 'REPORT_GENERATED',
    REPORT_FAILED = 'REPORT_FAILED',

    // Admin
    ADMIN_USER_SUSPENDED = 'ADMIN_USER_SUSPENDED',
    ADMIN_USER_ACTIVATED = 'ADMIN_USER_ACTIVATED',
    ADMIN_WORKSPACE_ACTION = 'ADMIN_WORKSPACE_ACTION',

    // Permission
    PERMISSION_DENIED = 'PERMISSION_DENIED',

    // Accounts
    ACCOUNT_TYPE_CREATED = 'ACCOUNT_TYPE_CREATED',
    ACCOUNT_TYPE_UPDATED = 'ACCOUNT_TYPE_UPDATED',
    ACCOUNT_TYPE_DELETED = 'ACCOUNT_TYPE_DELETED',
    ACCOUNT_CATEGORY_CREATED = 'ACCOUNT_CATEGORY_CREATED',
    ACCOUNT_CATEGORY_UPDATED = 'ACCOUNT_CATEGORY_UPDATED',
    ACCOUNT_CATEGORY_DELETED = 'ACCOUNT_CATEGORY_DELETED',
    ACCOUNT_CREATED = 'ACCOUNT_CREATED',
    ACCOUNT_UPDATED = 'ACCOUNT_UPDATED',
    ACCOUNT_ARCHIVED = 'ACCOUNT_ARCHIVED',
    ACCOUNT_UNARCHIVED = 'ACCOUNT_UNARCHIVED',
    ACCOUNT_DELETED = 'ACCOUNT_DELETED',

    // Direct Account Transactions
    ACCOUNT_TRANSACTION_DIRECT_CREATED = 'ACCOUNT_TRANSACTION_DIRECT_CREATED',
    ACCOUNT_TRANSACTION_DIRECT_UPDATED = 'ACCOUNT_TRANSACTION_DIRECT_UPDATED',
    ACCOUNT_TRANSACTION_DIRECT_DELETED = 'ACCOUNT_TRANSACTION_DIRECT_DELETED',

    // Wallet transfers
    ACCOUNT_TRANSFER_CREATED = 'ACCOUNT_TRANSFER_CREATED',
    ACCOUNT_TRANSFER_VOIDED = 'ACCOUNT_TRANSFER_VOIDED',
    ACCOUNT_BALANCE_RECALCULATED = 'ACCOUNT_BALANCE_RECALCULATED',

    // Obligations
    OBLIGATION_CREATED = 'OBLIGATION_CREATED',
    OBLIGATION_UPDATED = 'OBLIGATION_UPDATED',
    OBLIGATION_ARCHIVED = 'OBLIGATION_ARCHIVED',
    OBLIGATION_CANCELLED = 'OBLIGATION_CANCELLED',
    OBLIGATION_STATUS_CHANGED = 'OBLIGATION_STATUS_CHANGED',
    OBLIGATION_PAYMENT_APPLIED = 'OBLIGATION_PAYMENT_APPLIED',
    OBLIGATION_PAYMENT_REVERSED = 'OBLIGATION_PAYMENT_REVERSED',

    // Peer links (user-to-user obligation agreements)
    PEER_LINK_CREATED = 'PEER_LINK_CREATED',
    PEER_LINK_ACCEPTED = 'PEER_LINK_ACCEPTED',
    PEER_LINK_DECLINED = 'PEER_LINK_DECLINED',
    PEER_LINK_CANCELLED = 'PEER_LINK_CANCELLED',
    PEER_LINK_SETTLEMENT_CREATED = 'PEER_LINK_SETTLEMENT_CREATED',
    PEER_LINK_SETTLEMENT_CONFIRMED = 'PEER_LINK_SETTLEMENT_CONFIRMED',
    PEER_LINK_SETTLEMENT_REJECTED = 'PEER_LINK_SETTLEMENT_REJECTED',
    PEER_LINK_SETTLEMENT_CANCELLED = 'PEER_LINK_SETTLEMENT_CANCELLED',

    // Inventory
    INVENTORY_ITEM_CREATED = 'INVENTORY_ITEM_CREATED',
    INVENTORY_ITEM_UPDATED = 'INVENTORY_ITEM_UPDATED',
    INVENTORY_ITEM_DEACTIVATED = 'INVENTORY_ITEM_DEACTIVATED',
    INVENTORY_TRANSACTION_CREATED = 'INVENTORY_TRANSACTION_CREATED',
    INVENTORY_UNIT_CREATED = 'INVENTORY_UNIT_CREATED',
    INVENTORY_UNIT_UPDATED = 'INVENTORY_UNIT_UPDATED',
    INVENTORY_UNIT_DELETED = 'INVENTORY_UNIT_DELETED',
    ITEM_CATEGORY_CREATED = 'ITEM_CATEGORY_CREATED',
    ITEM_CATEGORY_UPDATED = 'ITEM_CATEGORY_UPDATED',
    ITEM_CATEGORY_DELETED = 'ITEM_CATEGORY_DELETED',
    INVENTORY_RENTAL_CREATED = 'INVENTORY_RENTAL_CREATED',

    // Cross-workspace agreements
    STOCK_TRANSFER_CREATED = 'STOCK_TRANSFER_CREATED',
    STOCK_TRANSFER_ACCEPTED = 'STOCK_TRANSFER_ACCEPTED',
    STOCK_TRANSFER_DECLINED = 'STOCK_TRANSFER_DECLINED',
    STOCK_TRANSFER_CANCELLED = 'STOCK_TRANSFER_CANCELLED',
    STOCK_TRANSFER_EXPENSE_RECORDED = 'STOCK_TRANSFER_EXPENSE_RECORDED',
    STOCK_TRANSFER_INCOME_RECORDED = 'STOCK_TRANSFER_INCOME_RECORDED',
    RENTAL_AGREEMENT_CREATED = 'RENTAL_AGREEMENT_CREATED',
    RENTAL_AGREEMENT_ACCEPTED = 'RENTAL_AGREEMENT_ACCEPTED',
    RENTAL_AGREEMENT_DECLINED = 'RENTAL_AGREEMENT_DECLINED',
    RENTAL_AGREEMENT_CANCELLED = 'RENTAL_AGREEMENT_CANCELLED',
    RENTAL_AGREEMENT_EXPENSE_RECORDED = 'RENTAL_AGREEMENT_EXPENSE_RECORDED',
    RENTAL_AGREEMENT_INCOME_RECORDED = 'RENTAL_AGREEMENT_INCOME_RECORDED',

    // Catalog (Tax + Product/Service)
    TAX_CREATED = 'TAX_CREATED',
    TAX_UPDATED = 'TAX_UPDATED',
    TAX_DELETED = 'TAX_DELETED',
    PRODUCT_SERVICE_CREATED = 'PRODUCT_SERVICE_CREATED',
    PRODUCT_SERVICE_UPDATED = 'PRODUCT_SERVICE_UPDATED',
    PRODUCT_SERVICE_DELETED = 'PRODUCT_SERVICE_DELETED',

    // Customer Profile
    CUSTOMER_PROFILE_CREATED = 'CUSTOMER_PROFILE_CREATED',
    CUSTOMER_PROFILE_UPDATED = 'CUSTOMER_PROFILE_UPDATED',

    // Invoicing
    INVOICE_CREATED = 'INVOICE_CREATED',
    INVOICE_UPDATED = 'INVOICE_UPDATED',
    INVOICE_SENT = 'INVOICE_SENT',
    INVOICE_VOIDED = 'INVOICE_VOIDED',
    INVOICE_PAYMENT_APPLIED = 'INVOICE_PAYMENT_APPLIED',
    INVOICE_DELETED = 'INVOICE_DELETED',
    INVOICE_SETTINGS_UPDATED = 'INVOICE_SETTINGS_UPDATED',

    // Projects
    PROJECT_CREATED = 'PROJECT_CREATED',
    PROJECT_UPDATED = 'PROJECT_UPDATED',
    PROJECT_ARCHIVED = 'PROJECT_ARCHIVED',
    PROJECT_UNARCHIVED = 'PROJECT_UNARCHIVED',
    PROJECT_DELETED = 'PROJECT_DELETED',
    PROJECT_MEMBER_ADDED = 'PROJECT_MEMBER_ADDED',
    PROJECT_MEMBER_REMOVED = 'PROJECT_MEMBER_REMOVED',
    PROJECT_MEMBER_ROLE_CHANGED = 'PROJECT_MEMBER_ROLE_CHANGED',

    // Tasks
    TASK_CREATED = 'TASK_CREATED',
    TASK_UPDATED = 'TASK_UPDATED',
    TASK_DELETED = 'TASK_DELETED',
    TASK_ASSIGNED = 'TASK_ASSIGNED',
    TASK_UNASSIGNED = 'TASK_UNASSIGNED',
    TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
    TASK_COMMENT_ADDED = 'TASK_COMMENT_ADDED',
    TASK_COMMENT_DELETED = 'TASK_COMMENT_DELETED',
    TASK_CHECKLIST_UPDATED = 'TASK_CHECKLIST_UPDATED',

    // Task approvals
    TASK_ASSIGNMENT_REQUESTED = 'TASK_ASSIGNMENT_REQUESTED',
    TASK_ASSIGNMENT_APPROVED = 'TASK_ASSIGNMENT_APPROVED',
    TASK_ASSIGNMENT_REJECTED = 'TASK_ASSIGNMENT_REJECTED',
    TASK_REPORT_SUBMITTED = 'TASK_REPORT_SUBMITTED',
    TASK_REPORT_APPROVED = 'TASK_REPORT_APPROVED',
    TASK_REPORT_REJECTED = 'TASK_REPORT_REJECTED',
    EXPENSE_CLAIM_SUBMITTED = 'EXPENSE_CLAIM_SUBMITTED',
    EXPENSE_CLAIM_APPROVED = 'EXPENSE_CLAIM_APPROVED',
    EXPENSE_CLAIM_REJECTED = 'EXPENSE_CLAIM_REJECTED',

    // People operations
    LEAVE_REQUESTED = 'LEAVE_REQUESTED',
    LEAVE_APPROVED = 'LEAVE_APPROVED',
    LEAVE_REJECTED = 'LEAVE_REJECTED',
    LEAVE_CANCELLED = 'LEAVE_CANCELLED',
    OVERTIME_REQUESTED = 'OVERTIME_REQUESTED',
    OVERTIME_APPROVED = 'OVERTIME_APPROVED',
    OVERTIME_REJECTED = 'OVERTIME_REJECTED',
    WORK_REPORT_SUBMITTED = 'WORK_REPORT_SUBMITTED',
    WORK_REPORT_APPROVED = 'WORK_REPORT_APPROVED',
    WORK_REPORT_REJECTED = 'WORK_REPORT_REJECTED',
    ATTENDANCE_FLAG_RAISED = 'ATTENDANCE_FLAG_RAISED',
    ATTENDANCE_FLAG_WAIVED = 'ATTENDANCE_FLAG_WAIVED',
    /** Cached balances recomputed from the ledger. Touches no journal. */
    LEDGER_BALANCES_REPAIRED = 'LEDGER_BALANCES_REPAIRED',
    WORK_SESSION_AUTO_CLOSED = 'WORK_SESSION_AUTO_CLOSED',

    // Time Tracking
    TIME_ENTRY_CREATED = 'TIME_ENTRY_CREATED',
    TIME_ENTRY_UPDATED = 'TIME_ENTRY_UPDATED',
    TIME_ENTRY_DELETED = 'TIME_ENTRY_DELETED',
    TIME_ENTRY_LOCKED = 'TIME_ENTRY_LOCKED',
    TIME_ENTRY_UNLOCKED = 'TIME_ENTRY_UNLOCKED',
    WORK_SESSION_CLOCKED_IN = 'WORK_SESSION_CLOCKED_IN',
    WORK_SESSION_CLOCKED_OUT = 'WORK_SESSION_CLOCKED_OUT',
    WORK_SESSION_CREATED = 'WORK_SESSION_CREATED',
    WORK_SESSION_UPDATED = 'WORK_SESSION_UPDATED',
    WORKSPACE_ATTENDANCE_SETTINGS_UPDATED = 'WORKSPACE_ATTENDANCE_SETTINGS_UPDATED',

    // Notifications
    NOTIFICATION_SENT = 'NOTIFICATION_SENT',
    RECEIPT_SENT = 'RECEIPT_SENT',

    // Ticketing
    WORKSPACE_FEATURE_ENABLED = 'WORKSPACE_FEATURE_ENABLED',
    WORKSPACE_FEATURE_DISABLED = 'WORKSPACE_FEATURE_DISABLED',
    MEMBER_STAFF_TAG_CHANGED = 'MEMBER_STAFF_TAG_CHANGED',
    TICKET_SETTINGS_UPDATED = 'TICKET_SETTINGS_UPDATED',
    TICKET_SESSION_CREATED = 'TICKET_SESSION_CREATED',
    TICKET_SESSION_UPDATED = 'TICKET_SESSION_UPDATED',
    TICKET_SESSION_DELETED = 'TICKET_SESSION_DELETED',
    TICKET_TYPE_CREATED = 'TICKET_TYPE_CREATED',
    TICKET_TYPE_UPDATED = 'TICKET_TYPE_UPDATED',
    TICKET_TYPE_DELETED = 'TICKET_TYPE_DELETED',
    TICKET_RULE_CREATED = 'TICKET_RULE_CREATED',
    TICKET_RULE_UPDATED = 'TICKET_RULE_UPDATED',
    TICKET_RULE_DELETED = 'TICKET_RULE_DELETED',
    TICKET_SALE_CREATED = 'TICKET_SALE_CREATED',
    TICKET_SALE_VOIDED = 'TICKET_SALE_VOIDED',
    TICKET_DAY_OPENED = 'TICKET_DAY_OPENED',
    TICKET_DAY_CLOSED = 'TICKET_DAY_CLOSED',
    TICKET_DAY_REOPENED = 'TICKET_DAY_REOPENED',
    TICKET_SHIFT_OPENED = 'TICKET_SHIFT_OPENED',
    TICKET_SHIFT_CLOSED = 'TICKET_SHIFT_CLOSED',
    MEMBERSHIP_TIER_CREATED = 'MEMBERSHIP_TIER_CREATED',
    MEMBERSHIP_TIER_UPDATED = 'MEMBERSHIP_TIER_UPDATED',
    MEMBERSHIP_ISSUED = 'MEMBERSHIP_ISSUED',
    MEMBERSHIP_UPDATED = 'MEMBERSHIP_UPDATED',
    MEMBERSHIP_RENEWED = 'MEMBERSHIP_RENEWED',
    MEMBERSHIP_REDEEMED = 'MEMBERSHIP_REDEEMED',

    // API Keys
    API_KEY_CREATED = 'API_KEY_CREATED',
    API_KEY_REVOKED = 'API_KEY_REVOKED',
    API_KEY_ROTATED = 'API_KEY_ROTATED',
    API_KEY_UPDATED = 'API_KEY_UPDATED',
    API_KEY_USED = 'API_KEY_USED',
}
