import 'reflect-metadata';
import { container } from 'tsyringe';
import { PrismaClient } from '@prisma/client';
import Redis from 'ioredis';
import { getPrismaClient } from './database';
import { getRedisClient } from './redis';

// ─── Infrastructure Singletons ─────────────────────────
container.register<PrismaClient>('PrismaClient', {
    useFactory: () => getPrismaClient(),
});

container.register<Redis>('RedisClient', {
    useFactory: () => getRedisClient(),
});

// ─── Repositories ──────────────────────────────────────
import { AuthRepository } from '../modules/auth/auth.repository';
import { CashbooksRepository } from '../modules/cashbooks/cashbooks.repository';
import { CategoriesRepository } from '../modules/categories/categories.repository';
import { ContactsRepository } from '../modules/contacts/contacts.repository';
import { EntriesRepository } from '../modules/entries/entries.repository';
import { MembersRepository } from '../modules/members/members.repository';
import { PaymentModesRepository } from '../modules/payment-modes/payment-modes.repository';
import { UsersRepository } from '../modules/users/users.repository';
import { WorkspacesRepository } from '../modules/workspaces/workspaces.repository';
import { InventoryRepository } from '../modules/inventory/inventory.repository';
import { ProjectsRepository } from '../modules/projects/projects.repository';
import { TasksRepository } from '../modules/tasks/tasks.repository';
import { TimeTrackingRepository } from '../modules/time-tracking/time-tracking.repository';

container.registerSingleton(AuthRepository);
container.registerSingleton(CashbooksRepository);
container.registerSingleton(CategoriesRepository);
container.registerSingleton(ContactsRepository);
container.registerSingleton(EntriesRepository);
container.registerSingleton(MembersRepository);
container.registerSingleton(PaymentModesRepository);
container.registerSingleton(UsersRepository);
container.registerSingleton(WorkspacesRepository);
container.registerSingleton(InventoryRepository);
container.registerSingleton(ProjectsRepository);
container.registerSingleton(TasksRepository);
container.registerSingleton(TimeTrackingRepository);

// ─── Services ──────────────────────────────────────────
import { AuthService } from '../modules/auth/auth.service';
import { CashbooksService } from '../modules/cashbooks/cashbooks.service';
import { CategoriesService } from '../modules/categories/categories.service';
import { ContactsService } from '../modules/contacts/contacts.service';
import { ContactLinksService } from '../modules/contact-links/contact-links.service';
import { ReferralsService } from '../modules/referrals/referrals.service';
import { PlatformSettingsService } from '../modules/platform/platform-settings.service';
import { StorageQuotaService } from '../modules/storage/storage-quota.service';
import { StorageController } from '../modules/storage/storage.controller';
import { AccountDeletionService } from '../modules/account-deletion/account-deletion.service';
import { AccountDeletionController } from '../modules/account-deletion/account-deletion.controller';
import { SupportService } from '../modules/support/support.service';
import { SupportController } from '../modules/support/support.controller';
import { WorkspaceProfileService } from '../modules/workspace-profile/workspace-profile.service';
import { EntriesService } from '../modules/entries/entries.service';
import { FilesService } from '../modules/files/files.service';
import { StorageService } from '../modules/files/storage.service';
import { MembersService } from '../modules/members/members.service';
import { PaymentModesService } from '../modules/payment-modes/payment-modes.service';
import { ReportsService } from '../modules/reports/reports.service';
import { UsersService } from '../modules/users/users.service';
import { WorkspacesService } from '../modules/workspaces/workspaces.service';
import { InvitesService } from '../modules/invites/invites.service';
import { MinioCleanupJob } from '../jobs/s3Cleanup';
import { InventoryService } from '../modules/inventory/inventory.service';
import { UnitsOfMeasureService } from '../modules/inventory/units-of-measure.service';
import { StockTransfersService } from '../modules/inventory/stock-transfers.service';
import { RentalAgreementsService } from '../modules/inventory/rental-agreements.service';
import { ProjectsService } from '../modules/projects/projects.service';
import { TasksService } from '../modules/tasks/tasks.service';
import { TicketingService } from '../modules/ticketing/ticketing.service';
import { TicketingConfigService } from '../modules/ticketing/ticketing-config.service';
import { MembershipsService } from '../modules/ticketing/memberships.service';
import { TicketingAnalyticsService } from '../modules/ticketing/ticketing-analytics.service';
import { PresenceService } from '../modules/attendance/presence.service';
import { AttendanceRollupService } from '../modules/attendance/rollup.service';
import { AttendanceService } from '../modules/attendance/attendance.service';
import { LeaveService } from '../modules/attendance/leave.service';
import { PeopleOpsService } from '../modules/attendance/people-ops.service';
import { AttendanceController } from '../modules/attendance/attendance.controller';
import { ExpenseClaimsService } from '../modules/expense-claims/expense-claims.service';
import { ExpenseClaimsController } from '../modules/expense-claims/expense-claims.controller';
import { TimeTrackingService } from '../modules/time-tracking/time-tracking.service';
import { NotificationsService } from '../modules/notifications/notifications.service';
import { PeerLinksService } from '../modules/peer-links/peer-links.service';
import { PlatformService } from '../modules/platform/platform.service';
import { LedgerReportsService } from '../modules/ledger-reports/ledger-reports.service';
import { ChartOfAccountsService } from '../modules/chart-of-accounts/chart-of-accounts.service';
import { PostingService } from '../core/ledger/posting.service';
import { LedgerIntegrityService } from '../core/ledger/integrity.service';

container.registerSingleton(AuthService);
container.registerSingleton(CashbooksService);
container.registerSingleton(CategoriesService);
container.registerSingleton(ContactsService);
container.registerSingleton(ContactLinksService);
container.registerSingleton(ReferralsService);
container.registerSingleton(PlatformSettingsService);
container.registerSingleton(StorageQuotaService);
container.registerSingleton(StorageController);
container.registerSingleton(AccountDeletionService);
container.registerSingleton(AccountDeletionController);
container.registerSingleton(SupportService);
container.registerSingleton(SupportController);
container.registerSingleton(WorkspaceProfileService);
container.registerSingleton(EntriesService);
container.registerSingleton(StorageService);
container.registerSingleton(FilesService);
container.registerSingleton(MembersService);
container.registerSingleton(PaymentModesService);
container.registerSingleton(ReportsService);
container.registerSingleton(UsersService);
container.registerSingleton(WorkspacesService);
container.registerSingleton(InvitesService);
container.registerSingleton(MinioCleanupJob);
container.registerSingleton(InventoryService);
container.registerSingleton(UnitsOfMeasureService);
container.registerSingleton(StockTransfersService);
container.registerSingleton(RentalAgreementsService);
container.registerSingleton(ProjectsService);
container.registerSingleton(TasksService);
container.registerSingleton(TicketingService);
container.registerSingleton(TicketingConfigService);
container.registerSingleton(MembershipsService);
container.registerSingleton(TicketingAnalyticsService);
container.registerSingleton(PresenceService);
container.registerSingleton(AttendanceRollupService);
container.registerSingleton(AttendanceService);
container.registerSingleton(LeaveService);
container.registerSingleton(PeopleOpsService);
container.registerSingleton(ExpenseClaimsService);
container.registerSingleton(TimeTrackingService);
container.registerSingleton(NotificationsService);
container.registerSingleton(PeerLinksService);
container.registerSingleton(PlatformService);
container.registerSingleton(LedgerReportsService);
container.registerSingleton(ChartOfAccountsService);
// The single writer of the ledger and of every cached balance.
container.registerSingleton(PostingService);
container.registerSingleton(LedgerIntegrityService);

// ─── Controllers ───────────────────────────────────────
import { AuthController } from '../modules/auth/auth.controller';
import { CashbooksController } from '../modules/cashbooks/cashbooks.controller';
import { CategoriesController } from '../modules/categories/categories.controller';
import { ContactsController } from '../modules/contacts/contacts.controller';
import { ContactLinksController } from '../modules/contact-links/contact-links.controller';
import { ReferralsController } from '../modules/referrals/referrals.controller';
import { WorkspaceProfileController } from '../modules/workspace-profile/workspace-profile.controller';
import { EntriesController } from '../modules/entries/entries.controller';
import { FilesController } from '../modules/files/files.controller';
import { MembersController } from '../modules/members/members.controller';
import { PaymentModesController } from '../modules/payment-modes/payment-modes.controller';
import { ReportsController } from '../modules/reports/reports.controller';
import { UsersController } from '../modules/users/users.controller';
import { WorkspacesController } from '../modules/workspaces/workspaces.controller';
import { PlatformController } from '../modules/platform/platform.controller';
import { AuditController } from '../modules/audit/audit.controller';
import { InvitesController } from '../modules/invites/invites.controller';
import { InventoryController } from '../modules/inventory/inventory.controller';
import { ProjectsController } from '../modules/projects/projects.controller';
import { TasksController } from '../modules/tasks/tasks.controller';
import { TicketingController } from '../modules/ticketing/ticketing.controller';
import { TimeTrackingController } from '../modules/time-tracking/time-tracking.controller';
import { NotificationsController } from '../modules/notifications/notifications.controller';
import { LedgerReportsController } from '../modules/ledger-reports/ledger-reports.controller';
import { ChartOfAccountsController } from '../modules/chart-of-accounts/chart-of-accounts.controller';

container.registerSingleton(AuthController);
container.registerSingleton(CashbooksController);
container.registerSingleton(CategoriesController);
container.registerSingleton(ContactsController);
container.registerSingleton(ContactLinksController);
container.registerSingleton(ReferralsController);
container.registerSingleton(WorkspaceProfileController);
container.registerSingleton(EntriesController);
container.registerSingleton(FilesController);
container.registerSingleton(MembersController);
container.registerSingleton(PaymentModesController);
container.registerSingleton(ReportsController);
container.registerSingleton(UsersController);
container.registerSingleton(WorkspacesController);
container.registerSingleton(PlatformController);
container.registerSingleton(AuditController);
container.registerSingleton(InvitesController);
container.registerSingleton(InventoryController);
container.registerSingleton(ProjectsController);
container.registerSingleton(TasksController);
container.registerSingleton(TicketingController);
container.registerSingleton(ExpenseClaimsController);
container.registerSingleton(AttendanceController);
container.registerSingleton(TimeTrackingController);
container.registerSingleton(NotificationsController);
container.registerSingleton(LedgerReportsController);
container.registerSingleton(ChartOfAccountsController);

export { container };
